export const PROCTORING_EVENTS = {
  FACE_PRESENT: 'FACE_PRESENT',
  NO_FACE: 'NO_FACE',
  MULTIPLE_FACES: 'MULTIPLE_FACES',
  CAMERA_DISABLED: 'CAMERA_DISABLED',
  DETECTION_UNAVAILABLE: 'DETECTION_UNAVAILABLE'
};
