/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect } from "react";

export function Avatar({ isSpeaking = false, ...props }) {
  const { nodes, materials } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
  const group = useRef();
  const blinkTimerRef = useRef(0);
  const nextBlinkTimeRef = useRef(3); // First blink after 3 seconds

  // Debug logging
  useEffect(() => {
    console.log('👄 Avatar Component - isSpeaking:', isSpeaking);
    
    // Log available eye morph targets
    if (nodes.EyeLeft && nodes.EyeLeft.morphTargetDictionary) {
      console.log('👁️ Left Eye Morph Targets:', Object.keys(nodes.EyeLeft.morphTargetDictionary));
    }
    if (nodes.EyeRight && nodes.EyeRight.morphTargetDictionary) {
      console.log('👁️ Right Eye Morph Targets:', Object.keys(nodes.EyeRight.morphTargetDictionary));
    }
  }, [isSpeaking, nodes]);

  // Lip Sync + Eye Blinking Animation
  useFrame((state, delta) => {
    // Head looks at camera
    if (group.current) {
      const head = group.current.getObjectByName("Head");
      if (head) {
        head.lookAt(state.camera.position);
      }
    }

    const time = state.clock.getElapsedTime();

    // ===== LIP SYNC ANIMATION =====
    if (isSpeaking) {
      const mouthOpen = (Math.sin(time * 15) + 1) / 2;
      
      // Apply to head
      if (nodes.Wolf3D_Head?.morphTargetDictionary?.["viseme_O"] !== undefined) {
        nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["viseme_O"]] = mouthOpen * 0.8;
      }
      
      // Apply to teeth
      if (nodes.Wolf3D_Teeth?.morphTargetDictionary?.["viseme_O"] !== undefined) {
        nodes.Wolf3D_Teeth.morphTargetInfluences[nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_O"]] = mouthOpen * 0.8;
      }
    } else {
      // Close mouth
      if (nodes.Wolf3D_Head?.morphTargetDictionary?.["viseme_O"] !== undefined) {
        nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["viseme_O"]] = 0;
      }
      if (nodes.Wolf3D_Teeth?.morphTargetDictionary?.["viseme_O"] !== undefined) {
        nodes.Wolf3D_Teeth.morphTargetInfluences[nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_O"]] = 0;
      }
    }

    // ===== EYE BLINKING ANIMATION (IMPROVED) =====
    blinkTimerRef.current += delta;

    // Time to blink?
    if (blinkTimerRef.current >= nextBlinkTimeRef.current) {
      const blinkProgress = (blinkTimerRef.current - nextBlinkTimeRef.current) / 0.2; // 200ms blink
      
      if (blinkProgress <= 1) {
        // Blink in progress
        const blinkAmount = Math.sin(blinkProgress * Math.PI); // 0 -> 1 -> 0
        
        console.log('👁️ Blinking:', blinkAmount.toFixed(2));
        
        // METHOD 1: Try morph targets
        const possibleBlinkTargets = [
          'eyeBlinkLeft', 'eyeBlinkRight', 'eyesClosed', 'blink', 
          'eyeBlink', 'EyeBlink', 'Blink', 'eyesClosedLeft', 'eyesClosedRight'
        ];
        
        // Apply to eye meshes
        [nodes.EyeLeft, nodes.EyeRight, nodes.Wolf3D_Head].forEach(mesh => {
          if (mesh?.morphTargetDictionary && mesh?.morphTargetInfluences) {
            possibleBlinkTargets.forEach(targetName => {
              const index = mesh.morphTargetDictionary[targetName];
              if (index !== undefined) {
                mesh.morphTargetInfluences[index] = blinkAmount;
                console.log(`✅ Applied ${targetName} on ${mesh.name}`);
              }
            });
          }
        });
        
        // METHOD 2: Scale-based blink (fallback if morph targets don't exist)
        const leftEye = group.current?.getObjectByName("EyeLeft");
        const rightEye = group.current?.getObjectByName("EyeRight");
        
        if (leftEye) {
          leftEye.scale.y = 1 - (blinkAmount * 0.9); // Close eye by scaling Y
        }
        if (rightEye) {
          rightEye.scale.y = 1 - (blinkAmount * 0.9);
        }
        
      } else {
        // Blink complete - reset
        blinkTimerRef.current = 0;
        nextBlinkTimeRef.current = 2.5 + Math.random() * 2.5; // 2.5-5 seconds
        
        // Reset morph targets
        [nodes.EyeLeft, nodes.EyeRight, nodes.Wolf3D_Head].forEach(mesh => {
          if (mesh?.morphTargetDictionary && mesh?.morphTargetInfluences) {
            Object.keys(mesh.morphTargetDictionary).forEach(key => {
              if (key.toLowerCase().includes('blink') || key.toLowerCase().includes('closed')) {
                mesh.morphTargetInfluences[mesh.morphTargetDictionary[key]] = 0;
              }
            });
          }
        });
        
        // Reset scale
        const leftEye = group.current?.getObjectByName("EyeLeft");
        const rightEye = group.current?.getObjectByName("EyeRight");
        if (leftEye) leftEye.scale.y = 1;
        if (rightEye) rightEye.scale.y = 1;
      }
    }
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");
