/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef, useEffect } from "react";
import * as THREE from "three";

export function Avatar({ avatarState = "idle", avatarBehavior = {}, ...props }) {
  const { nodes, materials, animations } = useGLTF("/models/646d9dcdc8a5f5bddbfac913.glb");
  const group = useRef();
  const { actions, names } = useAnimations(animations, group);
  const blinkTimerRef = useRef(0);
  const nextBlinkTimeRef = useRef(3);
  const avatarStateRef = useRef(avatarState);
  const avatarBehaviorRef = useRef(avatarBehavior);
  
  // Smoothing vectors
  const lookTarget = useRef(new THREE.Vector3(0, 0, 5));
  const currentLook = useRef(new THREE.Vector3(0, 0, 5));

  // Refs to actual rendered skinned meshes
  const headMeshRef = useRef();
  const teethMeshRef = useRef();

  useEffect(() => {
    avatarStateRef.current = avatarState;
  }, [avatarState]);

  useEffect(() => {
    avatarBehaviorRef.current = avatarBehavior || {};
    
    // Play animations from GLB if they exist
    const behavior = avatarBehavior || {};
    const animName = behavior.animation || "idle";
    const gestureName = behavior.gesture || "none";
    const speedStr = behavior.speaking_speed || "normal";
    
    let timeScale = 1.0;
    if (speedStr === "slow") timeScale = 0.8;
    if (speedStr === "fast") timeScale = 1.2;

    if (actions && names && names.length > 0) {
      if (actions[animName]) {
        actions[animName].reset().fadeIn(0.5).play();
        actions[animName].setEffectiveTimeScale(timeScale);
      }
      
      names.forEach(name => {
        if (name !== animName && name !== gestureName && actions[name]) {
          actions[name].fadeOut(0.5);
        }
      });

      if (gestureName !== "none" && actions[gestureName]) {
        actions[gestureName].reset().fadeIn(0.3).play();
      }
    }
  }, [avatarBehavior, actions, names]);

  // Lip Sync + Eye Blinking + Emotion Animation
  useFrame((state, delta) => {
    const time = state.clock.getElapsedTime();
    const behavior = avatarBehaviorRef.current;
    
    // Calculate Look Target based on head_direction and eye_contact
    const camPos = state.camera.position;
    if (behavior.head_direction === "notes") {
      lookTarget.current.set(camPos.x, camPos.y - 3, camPos.z);
    } else if (behavior.head_direction === "away") {
      lookTarget.current.set(camPos.x + 3, camPos.y + 1, camPos.z - 1);
    } else {
      // candidate or default
      if (behavior.eye_contact === false) {
        lookTarget.current.set(camPos.x + Math.sin(time) * 0.5, camPos.y + Math.cos(time * 0.8) * 0.5, camPos.z);
      } else {
        lookTarget.current.copy(camPos);
      }
    }

    // Lerp current look position for smooth head turning
    currentLook.current.lerp(lookTarget.current, delta * 3);

    // Apply Head Look and Posture
    if (group.current) {
      const head = group.current.getObjectByName("Head");
      if (head) head.lookAt(currentLook.current);

      const spine = group.current.getObjectByName("Spine");
      if (spine) {
        // Base posture
        let targetSpineRotX = behavior.posture === "leaning_forward" ? 0.15 : 0;
        
        // Gesture modifiers
        if (behavior.gesture === "nodding") {
          targetSpineRotX += Math.sin(state.clock.elapsedTime * 6) * 0.05;
        }
        
        spine.rotation.x = THREE.MathUtils.lerp(spine.rotation.x, targetSpineRotX, delta * 2);
      }
    }

    const speaking = avatarStateRef.current === "speaking" || behavior.animation === "speaking" || props.isSpeaking;

    // Get actual mesh refs
    const headMesh = headMeshRef.current;
    const teethMesh = teethMeshRef.current;

    // ===== LIP SYNC ANIMATION =====
    if (speaking && headMesh) {
      // Multiple sine waves at different frequencies for natural speech
      const jaw     = (Math.sin(time * 10) + 1) / 2;          // jaw open/close
      const lips    = (Math.sin(time * 7.3 + 0.8) + 1) / 2;   // lip rounding  
      const wide    = (Math.sin(time * 13.7 + 2.1) + 1) / 2;  // mouth width
      const subtle  = (Math.sin(time * 5.5 + 1.3) + 1) / 2;   // subtle variation

      const hd = headMesh.morphTargetDictionary;
      const hi = headMesh.morphTargetInfluences;
      
      if (hd && hi) {
        // Primary mouth open (viseme_O = "oh")
        if (hd["viseme_O"] !== undefined)  hi[hd["viseme_O"]]  = jaw * 0.8;
        // Mouth wide (viseme_aa = "ah")  
        if (hd["viseme_aa"] !== undefined) hi[hd["viseme_aa"]] = wide * 0.5;
        // Lip rounding (viseme_U = "oo")
        if (hd["viseme_U"] !== undefined)  hi[hd["viseme_U"]]  = lips * 0.3;
        // Smile/ee sound
        if (hd["viseme_E"] !== undefined)  hi[hd["viseme_E"]]  = subtle * 0.25;
        // Jaw open
        if (hd["jawOpen"] !== undefined)   hi[hd["jawOpen"]]   = jaw * 0.6;
      }

      // Teeth follow head
      if (teethMesh) {
        const td = teethMesh.morphTargetDictionary;
        const ti = teethMesh.morphTargetInfluences;
        if (td && ti) {
          if (td["viseme_O"] !== undefined)  ti[td["viseme_O"]]  = jaw * 0.8;
          if (td["viseme_aa"] !== undefined) ti[td["viseme_aa"]] = wide * 0.5;
          if (td["viseme_U"] !== undefined)  ti[td["viseme_U"]]  = lips * 0.3;
          if (td["viseme_E"] !== undefined)  ti[td["viseme_E"]]  = subtle * 0.25;
          if (td["jawOpen"] !== undefined)   ti[td["jawOpen"]]   = jaw * 0.6;
        }
      }
    } else {
      // Close mouth - smoothly lerp all visemes to 0
      const visemes = ["viseme_O", "viseme_aa", "viseme_U", "viseme_E", "jawOpen"];
      
      [headMesh, teethMesh].forEach(mesh => {
        if (!mesh?.morphTargetDictionary || !mesh?.morphTargetInfluences) return;
        const d = mesh.morphTargetDictionary;
        const i = mesh.morphTargetInfluences;
        visemes.forEach(v => {
          if (d[v] !== undefined && i[d[v]] > 0) {
            i[d[v]] = Math.max(0, i[d[v]] - delta * 8); // Smooth close
          }
        });
      });
    }

    // ===== EMOTION BLENDSHAPES =====
    if (headMesh?.morphTargetDictionary && headMesh?.morphTargetInfluences) {
      const d = headMesh.morphTargetDictionary;
      const i = headMesh.morphTargetInfluences;
      
      // Target states for emotions
      let tSmile = 0, tBrowDown = 0, tBrowUp = 0;
      
      if (behavior.emotion === "smile" || behavior.emotion === "happy") {
        tSmile = 0.6;
      } else if (behavior.emotion === "serious") {
        tBrowDown = 0.7;
      } else if (behavior.emotion === "thinking") {
        tBrowUp = 0.8;
      } else if (behavior.emotion === "encouraging" || behavior.emotion === "listening") {
        tSmile = 0.3;
        tBrowUp = 0.3;
      }
      
      // Lerp blendshapes smoothly
      const lerpFactor = delta * 4;
      if (d["mouthSmile"] !== undefined) i[d["mouthSmile"]] = THREE.MathUtils.lerp(i[d["mouthSmile"]], tSmile, lerpFactor);
      if (d["mouthSmileLeft"] !== undefined) i[d["mouthSmileLeft"]] = THREE.MathUtils.lerp(i[d["mouthSmileLeft"]], tSmile, lerpFactor);
      if (d["mouthSmileRight"] !== undefined) i[d["mouthSmileRight"]] = THREE.MathUtils.lerp(i[d["mouthSmileRight"]], tSmile, lerpFactor);
      
      if (d["browDownLeft"] !== undefined) i[d["browDownLeft"]] = THREE.MathUtils.lerp(i[d["browDownLeft"]], tBrowDown, lerpFactor);
      if (d["browDownRight"] !== undefined) i[d["browDownRight"]] = THREE.MathUtils.lerp(i[d["browDownRight"]], tBrowDown, lerpFactor);
      
      if (d["browInnerUp"] !== undefined) i[d["browInnerUp"]] = THREE.MathUtils.lerp(i[d["browInnerUp"]], tBrowUp, lerpFactor);
    }

    // ===== EYE BLINKING =====
    blinkTimerRef.current += delta;

    if (blinkTimerRef.current >= nextBlinkTimeRef.current) {
      const blinkProgress = (blinkTimerRef.current - nextBlinkTimeRef.current) / 0.15; // 150ms blink
      
      if (blinkProgress <= 1) {
        const blinkAmount = Math.sin(blinkProgress * Math.PI);
        
        // Use morph targets on head mesh for blinking
        if (headMesh?.morphTargetDictionary && headMesh?.morphTargetInfluences) {
          const bd = headMesh.morphTargetDictionary;
          const bi = headMesh.morphTargetInfluences;
          if (bd["eyeBlinkLeft"] !== undefined)  bi[bd["eyeBlinkLeft"]]  = blinkAmount;
          if (bd["eyeBlinkRight"] !== undefined) bi[bd["eyeBlinkRight"]] = blinkAmount;
        }

        // Scale-based fallback
        const leftEye = group.current?.getObjectByName("EyeLeft");
        const rightEye = group.current?.getObjectByName("EyeRight");
        if (leftEye)  leftEye.scale.y  = 1 - (blinkAmount * 0.9);
        if (rightEye) rightEye.scale.y = 1 - (blinkAmount * 0.9);
        
      } else {
        blinkTimerRef.current = 0;
        nextBlinkTimeRef.current = 2.5 + Math.random() * 2.5;
        
        // Reset blink
        if (headMesh?.morphTargetDictionary && headMesh?.morphTargetInfluences) {
          const bd = headMesh.morphTargetDictionary;
          const bi = headMesh.morphTargetInfluences;
          if (bd["eyeBlinkLeft"] !== undefined)  bi[bd["eyeBlinkLeft"]]  = 0;
          if (bd["eyeBlinkRight"] !== undefined) bi[bd["eyeBlinkRight"]] = 0;
        }
        
        const leftEye = group.current?.getObjectByName("EyeLeft");
        const rightEye = group.current?.getObjectByName("EyeRight");
        if (leftEye)  leftEye.scale.y  = 1;
        if (rightEye) rightEye.scale.y = 1;
      }
    }
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        ref={headMeshRef}
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        ref={teethMeshRef}
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/646d9dcdc8a5f5bddbfac913.glb");
